begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.app_workspaces (
  owner_id uuid primary key references auth.users(id) on delete cascade,
  schema_version integer not null default 1,
  revision bigint not null default 0,
  active_week_id text,
  to_mappings_locked boolean not null default false,
  extra_root jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.app_documents (
  owner_id uuid not null references auth.users(id) on delete cascade,
  document_key text not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (owner_id, document_key)
);

create table if not exists public.app_weeks (
  owner_id uuid not null references auth.users(id) on delete cascade,
  week_id text not null,
  position integer not null default 0,
  start_date date,
  end_date date,
  payload jsonb not null,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (owner_id, week_id)
);

create table if not exists public.app_tasks (
  owner_id uuid not null references auth.users(id) on delete cascade,
  task_key text not null,
  task_date date not null,
  position integer not null default 0,
  payload jsonb not null,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (owner_id, task_key)
);

create table if not exists public.app_discount_reservations (
  owner_id uuid not null references auth.users(id) on delete cascade,
  reservation_id text not null,
  position integer not null default 0,
  payload jsonb not null,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (owner_id, reservation_id)
);

create table if not exists public.app_attendance_records (
  owner_id uuid not null references auth.users(id) on delete cascade,
  record_key text not null,
  payload jsonb not null,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (owner_id, record_key)
);

create table if not exists public.app_backups (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  label text not null default 'Manual backup',
  payload jsonb not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists app_weeks_owner_position_idx
  on public.app_weeks (owner_id, position);
create index if not exists app_tasks_owner_date_position_idx
  on public.app_tasks (owner_id, task_date, position);
create index if not exists app_discount_reservations_owner_position_idx
  on public.app_discount_reservations (owner_id, position);
create index if not exists app_backups_owner_created_idx
  on public.app_backups (owner_id, created_at desc);

drop trigger if exists set_app_workspaces_updated_at on public.app_workspaces;
create trigger set_app_workspaces_updated_at
before update on public.app_workspaces
for each row execute function public.set_updated_at();

drop trigger if exists set_app_documents_updated_at on public.app_documents;
create trigger set_app_documents_updated_at
before update on public.app_documents
for each row execute function public.set_updated_at();

drop trigger if exists set_app_weeks_updated_at on public.app_weeks;
create trigger set_app_weeks_updated_at
before update on public.app_weeks
for each row execute function public.set_updated_at();

drop trigger if exists set_app_tasks_updated_at on public.app_tasks;
create trigger set_app_tasks_updated_at
before update on public.app_tasks
for each row execute function public.set_updated_at();

drop trigger if exists set_app_discount_reservations_updated_at on public.app_discount_reservations;
create trigger set_app_discount_reservations_updated_at
before update on public.app_discount_reservations
for each row execute function public.set_updated_at();

drop trigger if exists set_app_attendance_records_updated_at on public.app_attendance_records;
create trigger set_app_attendance_records_updated_at
before update on public.app_attendance_records
for each row execute function public.set_updated_at();

alter table public.app_workspaces enable row level security;
alter table public.app_documents enable row level security;
alter table public.app_weeks enable row level security;
alter table public.app_tasks enable row level security;
alter table public.app_discount_reservations enable row level security;
alter table public.app_attendance_records enable row level security;
alter table public.app_backups enable row level security;

create policy "Workspace owner access" on public.app_workspaces
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "Document owner access" on public.app_documents
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "Week owner access" on public.app_weeks
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "Task owner access" on public.app_tasks
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "Reservation owner access" on public.app_discount_reservations
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "Attendance owner access" on public.app_attendance_records
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "Backup owner access" on public.app_backups
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

revoke all on table public.app_workspaces from anon;
revoke all on table public.app_documents from anon;
revoke all on table public.app_weeks from anon;
revoke all on table public.app_tasks from anon;
revoke all on table public.app_discount_reservations from anon;
revoke all on table public.app_attendance_records from anon;
revoke all on table public.app_backups from anon;

grant select, insert, update, delete on table public.app_workspaces to authenticated;
grant select, insert, update, delete on table public.app_documents to authenticated;
grant select, insert, update, delete on table public.app_weeks to authenticated;
grant select, insert, update, delete on table public.app_tasks to authenticated;
grant select, insert, update, delete on table public.app_discount_reservations to authenticated;
grant select, insert, update, delete on table public.app_attendance_records to authenticated;
grant select, insert, update, delete on table public.app_backups to authenticated;
grant usage, select on sequence public.app_backups_id_seq to authenticated;

commit;
